const categories = [
  'Amazon Devices',
  'Apps & Games',
  'Arts, Crafts & Sewing',
  'Automotive',
  'Automotive Parts & Accessories',
  'Beauty & Personal Care',
  'Books',
  'CDs & Vinyl',
  'Cell Phones & Accessories',
  'Clothing & Accessories',
  'Clothing, Shoes & Jewelry',
  'Collectibles & Fine Art',
  'Computers',
  'Credit & Payment Cards',
  'Digital Music',
  'Echo & Alexa',
  'Electronics',
  'Food & Grocery',
  'Gift Cards',
  'Grocery & Gourmet Food',
  'Handmade',
  'Health & Household',
  'Health, Household & Baby Care',
  'Home & Business Services',
  'Home & Kitchen',
  'Industrial & Scientific',
  'Jewelry',
  'Kindle Store',
  'Luggage & Travel Gear',
  'Luxury Beauty',
  'Magazine Subscriptions',
  'Movies & TV',
  'Movies, Music & Games',
  'Music',
  'Musical Instruments',
  'Office Products',
  'Patio, Lawn & Garden',
  'Pet Supplies',
  'Prime Video',
  'Software',
  'Sports & Outdoors',
  'Toys & Games',
  'Tools & Home Improvement',
  'Video Games'
];

export default categories;  